---
- hosts: localhost
  become: true
  connection: local
  tasks:
  - name: remove apache2 package
    ansible.builtin.package:
      name: apache
      state: absent
  - shell: apt autoremove

- name: Get Status of webservers and append the new status to file
  hosts: webservers
  become: true

  tasks:

  - name: install apache2 package
    apt:
      name: apache2

  - name: Check Apache2 service status
    service:
      name: apache2
      state: started
    register: status
  - debug:
      var: status.state


